kind: pipeline
name: handlebars

steps:
  - name: check-handlebars-templates
    image: node
    commands:
      - npm install -g handlebars
      - ./check-handlebars-templates.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
