clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  handlebars:
    image: node
    commands:
      - npm install -g handlebars
      - ./check-handlebars-templates.sh
    when:
      matrix:
        TESTS: handlebars

matrix:
  include:
    - TESTS: handlebars
