language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=activity
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../core
  - ./occ check
  - ./occ status
  - ./occ app:list

script:
  - cd apps/$APP_NAME/

  # Test the app
  - sh -c "if [ '$CODECHECK' = '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
  - cd ../../
  - sh -c "if [ '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME; fi"
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - cd tests/
  - sh -c "if [ '$CODECHECK' != '1' ]; then phpunit --configuration phpunit.xml; fi"

  # Create coverage report
  - sh -c "if [ '$CODECHECK' != '1' -a '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$CODECHECK' != '1' -a '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  - cd ../

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: DB=oracle
    - php: 5.4
      env: DB=mysql;CODECHECK=1
  allow_failures:
    - php: hhvm
  fast_finish: true
