name: Cypress

on: pull_request

permissions:
  contents: read

concurrency: 
  group: cypress-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_NAME: activity
  CYPRESS_baseUrl: http://localhost:8081/index.php
  BRANCH: ${{ github.base_ref }}
  PHP_VERSION: 7.4

jobs:
  cypress:
    name: cypress
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout server
        uses: actions/checkout@v2
        with:
          repository: nextcloud/server
          submodules: true
          ref: ${{ env.BRANCH }}

      - name: Checkout ${{ env.APP_NAME }}
        uses: actions/checkout@v2
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, zip, gd, apcu
          coverage: none
          ini-values:
            apc.enable_cli=on

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
          PHP_CLI_SERVER_WORKERS: 10
        run: |
          mkdir data
          php occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          php occ config:system:set memcache.local --value="\\OC\\Memcache\\APCu"
          php -f index.php
          php -S 0.0.0.0:8081 &
          export OC_PASS=1234561
          php occ user:add --password-from-env user1
          php occ user:add --password-from-env user2
          php occ config:system:set force_language --value en
          php occ app:enable activity
          php occ app:list
          curl -v http://localhost:8081/index.php/login
          cat data/nextcloud.log

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: false # disabled for now as we have no way to savely use the token in our org
          parallel: false
          wait-on: '${{ env.CYPRESS_baseUrl }}'
          working-directory: 'apps/${{ env.APP_NAME }}'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
