name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  jest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    name: node${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
